spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 39.105.40.119  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:
  application:
    name: union
  datasource:
    url: jdbc:mysql://localhost:3306/union?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
info:
  app:
    img-url: http://39.105.40.119:8082/image/
    name: product
    desc: product
security:
  oauth2:
    resource:
      user-info-uri: https://jpk.akalisd.cn/authentication-center/user
      prefer-token-info: false
      jwt:
        keyUri: https://jpk.akalisd.cn/authentication-center/oauth/token_key
server:
  port: 8082
logging:
  level:
    root: info
    com:
      union: debug
pdd:
  client-id: 3d0d27ab85fe4fbd97982078d0e151c7
  client-secret: 62f2502cae0b3a117b475374ad5ffdc6fe8bc6b9
tb:
  server-url: http://gw.api.taobao.com/router/rest
  appkey: 28125995
  secret: 9f6a45fbeca9e587b098c7e08cd88fe1
jd:
  server-url: https://router.jd.com/api
  app-key: 3e1dab81d6a7fff6bf9ea03a010a0cc9
  app-secret: 853010a758434c15aaa575561cf3fefa
mgj:
  app-key: 101984
  app-secret: 7605401F40215EF8084E5DDAD8CA476C
  token-url: https://oauth.mogujie.com/token
  redirect-uri: https://akalisd.cn/api/redirectController/mgj/login
  server-url: https://openapi.mogujie.com/invoke
##  eureka配置
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:123456@39.105.40.119:9000/eureka/